arch_mapping:  # Map ansible architecture {{ ansible_architecture }} names to Docker's architecture names
  x86_64: amd64
  aarch64: arm64
htpasswd_name: matusik
htpasswd_password: matusik
user_name: vagrant